# Site settings
title: Single Line Alignment with Context
description: Information and interactive demos for the SLAC alignment system to enable compact DNA sequence alignment previews
author:
  name: Ryan Zujic

# Build settings
theme: jekyll-theme-cayman